### ISSUE TITLE
not showing messages on discord if data.timestamp < initTime.

### ISSUE THREAD

**Issue by LucaPierino** [DJWoodZ/Satisfactory-Discord-Bot#1]
In case the BOT has a different timezone from satisfactory server it cant work properly.

**Comment by DJWoodZ** [comment]
Thank you for this @LucaPierino.

There was a small omission in the parse function which caused the log file to be parsed in the local timezone instead of UTC. I've [updated the README](/DJWoodZ/Satisfactory-Discord-Bot#time-zones-and-log-files) with some information about this, but it should work now, no matter which time zones your hosts use.
